#!/bin/bash

PACKAGE=$1
SIBLING=${2-"../${PACKAGE}"}
if [[ -z "$PACKAGE" ]] ; then
  echo "usage $0 <package> [/full/non/sibling/path]"
  exit 1;
fi
echo setting up npm to use $PACKAGE from $SIBLING
( cd $SIBLING;
  pwd
  npm version
  npm link
)
pwd
# required eg when package names, like groups-api does not match repo
# name, armada
NAME=$(cat $SIBLING/package.json | tr -d '\n' | json -C name)
npm link "${NAME}"

